### PR TITLE
Merge Request for Issue/259 - help tip issues

### LINKED ISSUE #259: [bug] Help Tip popup messes up other UI highlighting
If the user mouses over a button (so it's highlighted) and the help pop up appears, the button stays highlighted until they mouse over another button and back.

### PR DESCRIPTION
**Pull request by erheine1**
Closes #259 

To test:
- When help tip is up, mouse over UI and make sure highlighting works in all cases
- Drag mouse in office view area and make sure buttons can't be clicked while dragging
- Click and drag a button and let go while help tip UI is visible and make sure button unhighlights
- Hold mouse down on button when help tips aren't up and let go when they are up and make sure button gets pressed

### CODE REVIEW

**Comment by CowboyCoderForever** [comment]
It seems like the Mouse Cursor changes whenever the Help Text UI is visible. Is this code responsible?

* Run the Intro scenario
* Click in the scene to focus on the office
* Wait for the help text to appear. Notice the cursor change.

**Comment by erheine1** [comment]
I moved the component that changes the cursor so now it'll change when over the visual part of the help tip and not the invisible clickable part that covers the whole screen.

**Comment by CowboyCoderForever** [comment]
Ah, found another issue. If you hover over the Play scenario button and click it without moving the cursor, it will stay in the Hand mode when the next scene is loaded.

Is that something you can fix in this code?

**Comment by erheine1** [comment]
No, that's a completely separate issue.  That'd either be a change in Ryan's cursor changing component or some way to reset the cursor when the scenario starts.

**Pull request merged**
