### PR TITLE
Merge Request for Issue/260 - character freeze on dialog up

### LINKED ISSUE #260: I want the characters to stop moving/animating when a dialog is opened
When any dialog is open, the game is in a semi-frozen state (time stops ticking). The characters should stop walking and animating.

There are `AnimationFreezer` and `CharacterPauser` scripts which may be useful.

### PR DESCRIPTION
**Pull request by erheine1**
Closes #260 

To test:
- Run Training/Stop Worms scenario
- Try to get camera in position so character is in corner (so they'll be visible while dialog is up)
- Proceed through scenario until message dialog pops up
- Make sure characters freeze while dialog is up

### CODE REVIEW

**Comment by CowboyCoderForever** [comment]
I think the CharacterPauser isn't getting unpaused when the dialog is closed. The animations start up again, but the avatar doesn't continue moving.

**Comment by erheine1** [comment]
CharacterPauser is getting toggled correctly just like the AnimationFreezer.  All the flags are right.  I'm not sure why they don't keep moving.  Is there other AI stuff that gets paused that I need to unpause or something?

**Comment by CowboyCoderForever** [comment]
> CharacterPauser is getting toggled correctly just like the AnimationFreezer. All the flags are right. I'm not sure why they don't keep moving. Is there other AI stuff that gets paused that I need to unpause or something?

I did a quick last-minute test of this last week and it seemed like the pausing was happening multiple times in a row. Can you see if that is true? Perhaps my CharacterPauser is not happy with repeated pause events.

**Comment by erheine1** [comment]
Yeah, I think I just found that same thing.  When you switch views, one "dialog" is closed and another "dialog" is up, so it calls that function with a false, then a true.  I have a fix for that, but I also discovered that if you click the Office tab to go back to the office, everything stays paused and I need to fix that.

**Pull request merged**
