### PR TITLE
Issue/165 purchase policy UI look and feel 2

### LINKED ISSUE #165: I want the purchase policy UI to look like the ui mockups
image

### PR DESCRIPTION
**Pull request by phfatmonkey**
Policy Purchase items look the way Ryan wants it. And what Ryan wants, he gets! Just kidding, that hardly ever happens.

To test, run the game and go to the Component or Zone view and notice the policy purchase items. They should look and function like (for the most part) this GIF:

purchase-item

Closes #165

### CODE REVIEW

**Comment by erheine1** [comment]
For some reason all the sections look grayed out until I interact with them once as folllows.
Before:
image
After:
image

Is this intended?

**Comment by erheine1** [comment]
Also, some of the longer named configuration settings aren't readable all the way.  I guess tooltips can help with this.

**Comment by phfatmonkey** [comment]
Ok, I see what you mean. What's happening is the "non-interactable toggle," the Policy Item:

image

is being set to Disabled somehow. I'm setting them to Selected or Normal, but on develop they were always set to Disabled. Any ideas about that?

**Comment by phfatmonkey** [comment]
Also, any thoughts on why it's doing this: 
image

**Pull request merged**
