### PR TITLE
Issue/249 offsite offices

### LINKED ISSUE #249: Implement Offsite Offices and Building UI
Some scenarios have offsite buildings (E.g. "Link Encryptors") that need to be visualized. Also need to implement the UI and keyboard shortcuts to jump the camera between buildings.

image

See the `organization.sdf` which lists which models to load.
```
     MainOfficeVersion: MS3B :end
     OffsiteOfficeVersion: none :end
     OffsiteOfficeVersion2: none :end
     OffsiteOfficeVersion3: none :end
     OffsiteOfficeVersion4: none :end
```

The OG game naming conventions:
`static const char MainOfficeVersionNames[4][16] = {"MS3A", "MS3B", "large", "small"};`
`static const char OffsiteOfficeVersionNames[5][16] = {"none", "home", "small_office", "www", "small"};`

**Offsites:**
homeoffice.rtb = "home"
homeoffice2.rtb = "small_office"
homeoffice3.rtb = "www"
smalloffice.rtb or office3b.rtb = "small"

**Main Offices:**
 office5.rtb = "MS3A"
office6.rtb = "MS3B"
office3b.rtb = "large"
? = "small"
? = "smallb"

**Unknown**
office3b.rtb = ""

Offsites to do:
- [x] "www"
- [x] "home"
- [x] "small_office"

### PR DESCRIPTION
**Pull request by CowboyCoderForever**
Closes #249 

This is turning into a monster branch as I keep having to pull in other branches into this one.

This activates the building next/prev UI buttons to cycle through the different buildings.
* I'm still not sure I totally have the building list accurate
* Load up any scenario that has multiple buildings and click the next/prev building buttons.
* Compare to the original game scenarios.

### CODE REVIEW

**Comment by erheine1** [comment]
Training/Identity Theft scenario loads both buildings, but the Buildings button don't cycle back to the main office like in the original game.

Building 1 (Sydney's House):
image

Building 2 (The Web):
image

**Comment by CowboyCoderForever** [comment]
...investigating...

**Comment by CowboyCoderForever** [comment]
Ok, found a timing issue bug. This might fix a couple other wonky things I was seeing.

**Comment by erheine1** [comment]
This may be nitpicky, but you have to click twice to go to the next building at first.  I'm guessing the first click takes you to the building you're already looking at?

**Comment by CowboyCoderForever** [comment]
> This may be nitpicky, but you have to click twice to go to the next building at first. I'm guessing the first click takes you to the building you're already looking at?

There are a few nitpicky issues in here that we probably want to tackle one at a time. This branch is already overloaded.

1) the initial view is supposed to be the first ViewPoint defined in the scenario, but for some reason is leaving the camera too far away.
2) The "building" viewpoint _is_ one of the regular ViewPoints, and the building button logic doesn't know if the player is looking at a ViewPoint from the Tab key or from the Building button UI.
3) Some ViewPoints should not available from the Tab key. Currently the code is not very smart about that and requires the Player to keep hitting Tab until a non-skipped ViewPoint comes around.

**Pull request merged**
